/// Flutter icons Kucharka
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kucharka
///      fonts:
///       - asset: fonts/Kucharka.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Kucharka {
  Kucharka._();

  static const _kFontFam = 'Kucharka';

  static const IconData restaurant_menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData emo_happy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emo_unhappy = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData emo_wink = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData glass = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData dinner = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pie = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pieregular = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData soup = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData soupregular = const IconData(0xe809, fontFamily: _kFontFam);
}
